use_frameworks!

platform :ios, '9.0'

target 'JIVerificationCodeWaitingView_Example' do
  pod 'JIVerificationCodeWaitingView', :path => '../'

  target 'JIVerificationCodeWaitingView_Tests' do
    inherit! :search_paths

    
  end
end
